# Generated by Django 4.1.5 on 2023-01-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_options_users_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
    ]
