# Generated by Django 4.2.10 on 2024-03-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_first_name_users_last_name_alter_users_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(help_text='email may be wrong', max_length=123, unique=True, verbose_name='email address'),
        ),
    ]
