# Generated by Django 4.2.10 on 2024-03-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0003_delete_createworkplaceview'),
        ('users', '0004_users_workplaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='workplaces',
        ),
        migrations.AddField(
            model_name='users',
            name='workplace1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplaces.workplace', verbose_name='workplaces1'),
        ),
    ]
