# Generated by Django 4.2.10 on 2024-03-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0003_delete_createworkplaceview'),
        ('users', '0005_remove_users_workplaces_users_workplace1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='workplace1',
        ),
        migrations.AddField(
            model_name='users',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplaces.workplace', verbose_name='workplaces'),
        ),
    ]
