# Generated by Django 4.2.10 on 2024-03-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0003_delete_createworkplaceview'),
        ('users', '0006_remove_users_workplace1_users_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplaces.workplace', verbose_name='workplace'),
        ),
    ]
