# Generated by Django 4.2.10 on 2024-03-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0003_delete_createworkplaceview'),
        ('users', '0009_alter_users_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplaces.workplace', verbose_name='workplace'),
        ),
    ]
