# Generated by Django 4.2.10 on 2024-02-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Workplace name')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '=Workplace=',
                'verbose_name_plural': '=Workplaces=',
                'ordering': ['-created_at'],
            },
        ),
    ]
