# Generated by Django 4.2.10 on 2024-02-23 12:03

import django.contrib.messages.views
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit
import task_manager.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateWorkplaceView',
            fields=[
                ('workplace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workplaces.workplace')),
            ],
            bases=(django.contrib.messages.views.SuccessMessageMixin, task_manager.mixins.LoginAuthMixin, 'workplaces.workplace', django.views.generic.edit.CreateView),
        ),
    ]
