# Generated by Django 4.2.10 on 2024-02-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0002_createworkplaceview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateWorkplaceView',
        ),
    ]
