exclude_patterns:
- "migrations/"
- "**/migrations/"
- "**/admin.py"
- "**/urls.py"
- "**/models.py"
- "task_manager/tests/"
- "task_manager/rollbar_middleware.py"
- "**/views.py"
- "labels/views.py"
- "static/"