# Generated by Django 4.2.10 on 2024-03-07 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statuses', '0004_alter_status_id'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='Time')),
                ('description', models.TextField(max_length=333, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Worker name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Product name')),
                ('status', models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='statuses.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'WorkDay',
                'verbose_name_plural': '-=WorkDays=-',
                'ordering': ['-created_at'],
            },
        ),
    ]
