# Generated by Django 4.2.10 on 2024-03-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=222, unique=True, verbose_name='Worker name')),
                ('time', models.IntegerField(verbose_name='Time')),
                ('description', models.TextField(max_length=333, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product name')),
            ],
            options={
                'verbose_name': 'WorkDay',
                'verbose_name_plural': '-=WorkDays=-',
                'ordering': ['-created_at'],
            },
        ),
    ]
