# Generated by Django 4.2.10 on 2024-03-09 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_status_1_product_status_2_product_status_3'),
        ('labels', '0005_alter_labels_id'),
        ('statuses', '0004_alter_status_id'),
        ('workdays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.labels', verbose_name='Operation'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statuses.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Worker name'),
        ),
    ]
