# Generated by Django 4.2.10 on 2024-03-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workday',
            old_name='name',
            new_name='user',
        ),
    ]
