# Generated by Django 4.2.10 on 2024-03-06 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workdays', '0002_alter_workday_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Worker name'),
        ),
    ]
