# Generated by Django 4.2.10 on 2024-03-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0002_workday_operation_alter_workday_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='time',
            field=models.FloatField(verbose_name='Time of create'),
        ),
    ]
