# Generated by Django 4.2.10 on 2024-03-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0004_alter_status_id'),
        ('workdays', '0002_rename_name_workday_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='description',
            field=models.TextField(blank=True, max_length=333, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='status',
            field=models.ForeignKey(default=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='statuses.status', verbose_name='Status1'),
        ),
    ]
