# Generated by Django 4.2.10 on 2024-03-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_alter_labels_id'),
        ('workdays', '0003_alter_workday_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.labels', verbose_name='Operation'),
        ),
    ]
