# Generated by Django 4.2.10 on 2024-03-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0003_alter_workday_description_alter_workday_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='workplace_name',
            field=models.CharField(max_length=222, null=True, verbose_name='Workplace'),
        ),
    ]
