# Generated by Django 4.2.10 on 2024-03-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0004_alter_workday_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='time',
            field=models.FloatField(blank=True, verbose_name='Time of create'),
        ),
    ]
