# Generated by Django 4.2.10 on 2024-03-07 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workdays', '0005_rename_user_workday_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Worker name'),
        ),
    ]
