# Generated by Django 4.2.10 on 2024-03-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0006_alter_workday_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='time',
            field=models.FloatField(verbose_name='Time of create'),
        ),
    ]
