# Generated by Django 4.2.10 on 2024-03-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0003_delete_createworkplaceview'),
        ('workdays', '0007_alter_workday_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='workplace_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplaces.workplace', verbose_name='Workplace'),
        ),
    ]
