# Generated by Django 4.2.10 on 2024-03-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0008_alter_workday_workplace_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workday',
            old_name='workplace_name',
            new_name='workplace',
        ),
    ]
