# Generated by Django 4.2.10 on 2024-03-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0009_rename_workplace_name_workday_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во'),
        ),
    ]
