# Generated by Django 4.2.10 on 2024-03-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdays', '0010_workday_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
    ]
