# Generated by Django 4.1.5 on 2023-01-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='имя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
