# Generated by Django 4.1.5 on 2023-01-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': '=Status=', 'verbose_name_plural': '=Statuses='},
        ),
        migrations.AddField(
            model_name='status',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
    ]
