# Generated by Django 4.1.5 on 2023-01-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_labels_options'),
        ('tasks', '0005_tasklabel_task_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklabel',
            old_name='label',
            new_name='labels',
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='tasks.TaskLabel', to='labels.labels', verbose_name='Label'),
        ),
    ]
