# Generated by Django 4.2.10 on 2024-03-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0003_delete_createworkplaceview'),
        ('tasks', '0013_task_status_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplaces.workplace'),
        ),
    ]
