# Generated by Django 4.2.10 on 2024-04-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Task name'),
        ),
    ]
