# Generated by Django 4.2.10 on 2024-04-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_alter_labels_id'),
        ('tasks', '0023_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='tasks.TaskLabel', to='labels.labels', verbose_name='Labels'),
        ),
    ]
