# Generated by Django 4.2.10 on 2024-03-11 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overtimes', '0002_alter_overtime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Worker name'),
        ),
    ]
