# Generated by Django 4.2.10 on 2024-03-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimes', '0003_alter_overtime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='time',
            field=models.FloatField(default=0, verbose_name='Overtime'),
        ),
    ]
