# Generated by Django 4.2.10 on 2024-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtimes', '0005_alter_overtime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='time',
            field=models.FloatField(help_text='Write you ovetime.', verbose_name='Overtime'),
        ),
    ]
