# Generated by Django 4.1.5 on 2023-01-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_labels_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labels',
            options={'ordering': ['-created_at'], 'verbose_name': '=Label=', 'verbose_name_plural': '=Labels='},
        ),
    ]
