# Generated by Django 4.1.5 on 2023-02-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_alter_labels_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='labels',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
