# Generated by Django 4.2.10 on 2024-02-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_alter_labels_created_at_alter_labels_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
