# Generated by Django 4.2.10 on 2024-02-29 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workplaces', '0003_delete_createworkplaceview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222, unique=True, verbose_name='Tool name')),
                ('description', models.TextField(blank=True, max_length=333, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('workplace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workplaces.workplace', verbose_name='Workplace')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': '-=Tools=-',
                'ordering': ['-created_at'],
            },
        ),
    ]
