# Generated by Django 4.2.10 on 2024-03-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_tool_workplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='name',
            new_name='type',
        ),
    ]
