# Generated by Django 4.2.10 on 2024-03-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_rename_name_tool_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='D',
            field=models.FloatField(blank=True, null=True, verbose_name='D, mm'),
        ),
        migrations.AddField(
            model_name='tool',
            name='L',
            field=models.FloatField(blank=True, null=True, verbose_name='L, mm'),
        ),
        migrations.AddField(
            model_name='tool',
            name='Lc',
            field=models.FloatField(blank=True, null=True, verbose_name='Lc, mm'),
        ),
        migrations.AddField(
            model_name='tool',
            name='R',
            field=models.FloatField(blank=True, null=True, verbose_name='R'),
        ),
        migrations.AddField(
            model_name='tool',
            name='Z',
            field=models.FloatField(blank=True, null=True, verbose_name='Z, amount'),
        ),
        migrations.AddField(
            model_name='tool',
            name='company',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='tool',
            name='delivery_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Delivery time, days'),
        ),
        migrations.AddField(
            model_name='tool',
            name='departure',
            field=models.FloatField(blank=True, null=True, verbose_name='Depart, mm'),
        ),
        migrations.AddField(
            model_name='tool',
            name='dm',
            field=models.FloatField(blank=True, null=True, verbose_name='d, mm'),
        ),
        migrations.AddField(
            model_name='tool',
            name='monolith',
            field=models.BooleanField(blank=True, null=True, verbose_name='Monolith'),
        ),
        migrations.AddField(
            model_name='tool',
            name='name_plate',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Name of plate'),
        ),
        migrations.AddField(
            model_name='tool',
            name='plate',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Plate'),
        ),
        migrations.AddField(
            model_name='tool',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price, Rub'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(blank=True, max_length=222, null=True, unique=True, verbose_name='Type tool'),
        ),
    ]
