# Generated by Django 4.2.10 on 2024-03-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_rename_name_plate_tool_plate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='dm',
            field=models.FloatField(blank=True, default='', null=True, verbose_name='d, mm'),
        ),
    ]
