# Generated by Django 4.2.10 on 2024-03-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_alter_tool_dm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='dm',
            field=models.FloatField(blank=True, null=True, verbose_name='d, mm'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Type tool'),
        ),
    ]
