# Generated by Django 4.2.10 on 2024-03-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_alter_tool_dm_alter_tool_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(blank=True, max_length=333, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='dm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='d, mm'),
        ),
    ]
