# Generated by Django 4.2.10 on 2024-03-07 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statuses', '0004_alter_status_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222, verbose_name='Product name')),
                ('number', models.CharField(max_length=222, verbose_name='Product number')),
                ('description', models.TextField(max_length=333, verbose_name='Description')),
                ('step_1', models.CharField(blank=True, default='111', max_length=222, verbose_name='Step_1')),
                ('step_2', models.BooleanField(default='', verbose_name='Step_2')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statuses.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': '-=Products=-',
                'ordering': ['-created_at'],
            },
        ),
    ]
