# Generated by Django 4.2.10 on 2024-03-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222, verbose_name='Product name')),
                ('number', models.IntegerField(verbose_name='Product number')),
                ('description', models.TextField(blank=True, max_length=333, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': '-=Products=-',
                'ordering': ['-created_at'],
            },
        ),
    ]
