# Generated by Django 4.2.10 on 2024-03-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0004_alter_status_id'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=333, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statuses.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='step_1',
            field=models.CharField(blank=True, max_length=222, verbose_name='Step_1'),
        ),
    ]
