# Generated by Django 4.2.10 on 2024-03-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='step_1',
            field=models.BooleanField(blank=True, default=False, verbose_name='Step_1'),
        ),
    ]
