# Generated by Django 4.2.10 on 2024-03-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_step_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='step_1',
            field=models.CharField(blank=True, default='', max_length=222, verbose_name='Step_1'),
        ),
    ]
