# Generated by Django 4.2.10 on 2024-03-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0004_alter_status_id'),
        ('products', '0002_alter_product_description_alter_product_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='step_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='step_2',
        ),
        migrations.AddField(
            model_name='product',
            name='status1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status1', to='statuses.status', verbose_name='Clear_1'),
        ),
        migrations.AddField(
            model_name='product',
            name='status2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status2', to='statuses.status', verbose_name='Clear_2'),
        ),
        migrations.AddField(
            model_name='product',
            name='status3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status3', to='statuses.status', verbose_name='Clear_3'),
        ),
    ]
