# Generated by Django 4.2.10 on 2024-03-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0003_delete_createworkplaceview'),
        ('products', '0004_product_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='clear_turning_first',
        ),
        migrations.RemoveField(
            model_name='product',
            name='clear_turning_second',
        ),
        migrations.RemoveField(
            model_name='product',
            name='clear_turning_third',
        ),
        migrations.AddField(
            model_name='product',
            name='step_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Step_1', to='workplaces.workplace', verbose_name='Step_1'),
        ),
        migrations.AddField(
            model_name='product',
            name='step_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Step_2', to='workplaces.workplace', verbose_name='Step_2'),
        ),
        migrations.AddField(
            model_name='product',
            name='step_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Step_3', to='workplaces.workplace', verbose_name='Step_3'),
        ),
    ]
