# Generated by Django 4.2.10 on 2024-03-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0003_delete_createworkplaceview'),
        ('products', '0005_remove_product_clear_turning_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='step_3',
            field=models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Step_3', to='workplaces.workplace', verbose_name='Step_3'),
        ),
    ]
