# Generated by Django 4.2.10 on 2024-03-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_color1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='color_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color1',
            new_name='color_2',
        ),
        migrations.AddField(
            model_name='product',
            name='color_3',
            field=models.CharField(blank=True, max_length=29, null=True),
        ),
    ]
