# Generated by Django 4.2.10 on 2024-03-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0003_delete_createworkplaceview'),
        ('products', '0010_rename_color_product_color_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_4',
            field=models.CharField(blank=True, max_length=29, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_5',
            field=models.CharField(blank=True, max_length=29, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_6',
            field=models.CharField(blank=True, max_length=29, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='step_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Step_4', to='workplaces.workplace', verbose_name='Step_4'),
        ),
        migrations.AddField(
            model_name='product',
            name='step_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Step_5', to='workplaces.workplace', verbose_name='Step_5'),
        ),
        migrations.AddField(
            model_name='product',
            name='step_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Step_6', to='workplaces.workplace', verbose_name='Step_6'),
        ),
    ]
