# Generated by Django 4.2.10 on 2024-04-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spec_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во'),
        ),
    ]
